(() => {
  const cfg=window.MANTO_CONFIG||{};
  const PRICES={Básico:Number(cfg.BASIC_PRICE||65.00),Premium:Number(cfg.PREMIUM_PRICE||85.00)};
  const COSTS={Básico:Number(cfg.BASIC_COST||55),Premium:Number(cfg.PREMIUM_COST||70)};
  const STATUSES=['Novo','Aguardando pagamento','Pago','Em produção','Pronto','Entregue','Cancelado'];
  const PAID=['Pago','Em produção','Pronto','Entregue'];
  const remote=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY);
  let orders=[],token=sessionStorage.getItem('manto_access_token')||'',editSeq=0;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  if(!remote) $$('.remote-login').forEach(x=>x.classList.add('hidden'));

  function itemCost(i){return Number(i.unitCost ?? COSTS[i.model] ?? 0)*Number(i.quantity||0)}
  function itemRevenue(i){return Number(i.unitPrice ?? PRICES[i.model] ?? 0)*Number(i.quantity||0)}
  function recalc(o){const subtotal=(o.items||[]).reduce((s,i)=>s+itemRevenue(i),0),totalCost=(o.items||[]).reduce((s,i)=>s+itemCost(i),0),discount=Math.max(0,Number(o.discount||0)),total=Math.max(0,subtotal-discount),profit=total-totalCost;return {...o,subtotal,totalCost,discount,total,profit};}
  function normalize(o){return recalc({...o,source:o.source||'Site',items:(o.items||[]).map(i=>({...i,unitPrice:Number(i.unitPrice??PRICES[i.model]??0),unitCost:Number(i.unitCost??COSTS[i.model]??0),quantity:Number(i.quantity||1)}))});}

  async function login(email,password){if(!remote){if(password!=='admin')throw new Error('Senha incorreta. No modo demonstração, use admin.');return'demo';}const r=await fetch(`${cfg.SUPABASE_URL.replace(/\/$/,'')}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error_description||d.msg||'Não foi possível entrar.');return d.access_token;}
  async function listOrders(){if(!remote)return JSON.parse(localStorage.getItem('manto_orders')||'[]').map(normalize);const r=await fetch(`${cfg.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/orders?select=*&order=created_at.desc`,{headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Não foi possível carregar os pedidos.');return(await r.json()).map(x=>normalize({orderId:x.order_id,createdAt:x.created_at_display||x.created_at,name:x.customer_name,whatsapp:x.whatsapp,city:x.city,delivery:x.delivery,payment:x.payment,neighborhood:x.neighborhood,address:x.address,addressNumber:x.address_number,complement:x.complement,notes:x.notes,items:x.items||[],subtotal:Number(x.subtotal||0),discount:Number(x.discount||0),total:Number(x.total||0),totalCost:Number(x.total_cost||0),profit:Number(x.profit||0),status:x.status||'Novo',source:x.source||'Site'}));}
  function localSave(order,isNew){let a=JSON.parse(localStorage.getItem('manto_orders')||'[]');if(isNew)a.unshift(order);else a=a.map(o=>o.orderId===order.orderId?order:o);localStorage.setItem('manto_orders',JSON.stringify(a));}
  async function saveOrder(order,isNew){order=normalize(order);if(!remote){localSave(order,isNew);return order;}const row={order_id:order.orderId,created_at_display:order.createdAt,customer_name:order.name,whatsapp:order.whatsapp,city:order.city,delivery:order.delivery,payment:'Dinheiro ou PIX',notes:order.notes,items:order.items,subtotal:order.subtotal,discount:order.discount,total:order.total,total_cost:order.totalCost,profit:order.profit,status:order.status,source:order.source||'Manual'};const url=isNew?`${cfg.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/orders`:`${cfg.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/orders?order_id=eq.${encodeURIComponent(order.orderId)}`;const r=await fetch(url,{method:isNew?'POST':'PATCH',headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error('Não foi possível salvar o pedido. Confira o SQL e as permissões do Supabase.');return order;}
  async function updateStatus(orderId,status){const o=orders.find(x=>x.orderId===orderId);if(!o)return;await saveOrder({...o,status},false);}

  function showDash(){$('#login-screen').classList.add('hidden');$('#dashboard').classList.remove('hidden');load();}
  function showLogin(){$('#dashboard').classList.add('hidden');$('#login-screen').classList.remove('hidden');}
  $('#login-form').onsubmit=async e=>{e.preventDefault();try{token=await login($('#admin-email')?.value.trim()||'',$('#admin-password').value);sessionStorage.setItem('manto_access_token',token);showDash();}catch(err){$('#login-message').innerHTML=`<div class="form-message error">${esc(err.message)}</div>`;}};
  $('#logout-btn').onclick=()=>{sessionStorage.removeItem('manto_access_token');token='';showLogin();};
  $('#refresh-btn').onclick=load;$('#search-input').oninput=renderTable;$('#status-filter').onchange=renderTable;$('#csv-btn').onclick=exportCsv;
  $$('.admin-nav[data-view]').forEach(b=>b.onclick=()=>{$$('.admin-nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.admin-view').forEach(v=>v.classList.remove('active'));$(`#view-${b.dataset.view}`).classList.add('active');});

  async function load(){try{orders=await listOrders();$('#admin-message').innerHTML=remote?'':'<div class="form-message success">Modo demonstração: os pedidos ficam somente neste navegador.</div>';render();}catch(err){$('#admin-message').innerHTML=`<div class="form-message error">${esc(err.message)}</div>`;}}
  function render(){orders=orders.map(normalize);renderMetrics();renderPie();renderProduction();renderTable();renderReports();}
  function activeOrders(){return orders.filter(o=>o.status!=='Cancelado');}
  function renderMetrics(){const a=activeOrders(),qty=a.flatMap(o=>o.items||[]).reduce((s,i)=>s+Number(i.quantity||0),0),rev=a.reduce((s,o)=>s+o.total,0),profit=a.reduce((s,o)=>s+o.profit,0);$('#metric-orders').textContent=orders.length;$('#metric-qty').textContent=qty;$('#metric-revenue').textContent=brl(rev);$('#metric-profit').textContent=brl(profit);}
  function renderPie(){let basic=0,premium=0;activeOrders().flatMap(o=>o.items||[]).forEach(i=>{if(i.model==='Básico')basic+=Number(i.quantity||0);if(i.model==='Premium')premium+=Number(i.quantity||0);});const total=basic+premium,pct=total?basic/total*100:50;$('#model-pie').style.background=`conic-gradient(var(--red2) 0 ${pct}%, var(--gold) ${pct}% 100%)`;$('#pie-basic').textContent=basic;$('#pie-premium').textContent=premium;}
  function renderProduction(){const map={};activeOrders().flatMap(o=>o.items||[]).forEach(i=>{const k=`${i.model}|${i.category}|${i.size}${i.childAge?` (${i.childAge} anos)`:''}`;map[k]=(map[k]||0)+Number(i.quantity||0);});const rows=Object.entries(map).sort((a,b)=>b[1]-a[1]);$('#production-list').innerHTML=rows.length?rows.map(([k,v])=>{const[m,c,s]=k.split('|');return`<div class="production-row"><div><b>${esc(m)}</b><small>${esc(c)} · Tam. ${esc(s)}</small></div><strong>${v}</strong></div>`}).join(''):'<div class="empty">Nenhuma camisa ainda.</div>';}
  function filtered(){const q=$('#search-input').value.trim().toLowerCase(),st=$('#status-filter').value;return orders.filter(o=>`${o.orderId} ${o.name} ${o.whatsapp} ${o.city} ${(o.items||[]).map(i=>`${i.model} ${i.category} ${i.size}`).join(' ')}`.toLowerCase().includes(q)&&(st==='Todos'||o.status===st));}
  function itemsHtml(items){return(items||[]).map(i=>`<div class="order-line"><b>${Number(i.quantity||0)}x</b> ${esc(i.model)} · ${esc(i.category)} · <span>${esc(i.size)}</span>${i.childAge?` · ${i.childAge} anos`:''}</div>`).join('');}
  function cleanWhatsapp(value){let num=String(value||'').replace(/\D/g,'');if(num.startsWith('55'))num=num.slice(2);return num;}
  function whatsappLink(o){const num=cleanWhatsapp(o.whatsapp);const text=encodeURIComponent(`Olá, ${o.name}! Estou entrando em contato sobre o pedido ${o.orderId} do Manto Monumental.`);return`https://wa.me/55${num}?text=${text}`;}
  function paymentDeadlineInfo(){
    // Prazo comercial fixo: 29/08/2026. Usamos datas locais sem horário para evitar variação de fuso.
    const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),deadline=new Date(2026,7,29);
    const diff=Math.round((deadline-today)/86400000);
    if(diff>1)return{days:diff,label:`Faltam ${diff} dias para o pagamento`,sentence:`Faltam ${diff} dias para o prazo de pagamento, que encerra em 29/08.`};
    if(diff===1)return{days:1,label:'Falta 1 dia para o pagamento',sentence:'Falta apenas 1 dia para o prazo de pagamento, que encerra amanhã, 29/08.'};
    if(diff===0)return{days:0,label:'Pagamento vence hoje',sentence:'O prazo de pagamento encerra hoje, 29/08.'};
    const overdue=Math.abs(diff);return{days:diff,label:`Prazo vencido há ${overdue} dia${overdue===1?'':'s'}`,sentence:`O prazo de pagamento encerrou em 29/08, há ${overdue} dia${overdue===1?'':'s'}.`};
  }
  function chargeWhatsappLink(o){
    const num=cleanWhatsapp(o.whatsapp),d=paymentDeadlineInfo(),items=(o.items||[]).map(i=>`${Number(i.quantity||1)}x ${i.model} ${i.category} ${i.size}`).join(', ');
    const text=encodeURIComponent(`Olá, ${o.name}! Tudo bem? Passando para lembrar do pagamento do seu pedido ${o.orderId} do Manto Monumental. ${d.sentence}\n\nPedido: ${items||'Manto Monumental'}\nValor a pagar: ${brl(o.total)}\nPrazo: 29/08/2026\n\nImportante: somente as camisas pagas até a data limite serão incluídas no pedido ao fornecedor em 01/09. Se você já efetuou o pagamento, por favor desconsidere esta mensagem. Obrigado!`);
    return`https://wa.me/55${num}?text=${text}`;
  }
  function renderTable(){const list=filtered();$('#result-count').textContent=list.length;$('#table-empty').classList.toggle('hidden',!!list.length);$('#orders-body').innerHTML=list.map(o=>`<tr><td><b>${esc(o.orderId)}</b><br><small class="muted">${esc(o.createdAt)}</small><br><small class="source-tag">${esc(o.source||'Site')}</small></td><td>${esc(o.name)}<br><small class="muted">${esc(o.whatsapp)}</small></td><td class="lines-cell">${itemsHtml(o.items)}</td><td><b>${brl(o.total)}</b><br><small class="muted">Bruto ${brl(o.subtotal)}</small></td><td>${o.discount?`<b class="discount-value">-${brl(o.discount)}</b>`:'—'}</td><td><b class="profit-value">${brl(o.profit)}</b><br><small class="muted">Custo ${brl(o.totalCost)}</small></td><td><select class="status-select" data-order="${esc(o.orderId)}">${STATUSES.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td><td><div class="row-actions"><a class="icon-btn whatsapp-btn" href="${whatsappLink(o)}" target="_blank" title="Abrir WhatsApp do cliente">WhatsApp</a>${['Novo','Aguardando pagamento'].includes(o.status)?`<a class="icon-btn charge-btn" href="${chargeWhatsappLink(o)}" target="_blank" title="Enviar cobrança pelo WhatsApp">Cobrar</a>`:''}<button class="icon-btn edit-btn" data-order="${esc(o.orderId)}" type="button">Editar</button></div></td></tr>`).join('');$$('.status-select').forEach(s=>s.onchange=async e=>{try{await updateStatus(e.target.dataset.order,e.target.value);orders=orders.map(o=>o.orderId===e.target.dataset.order?normalize({...o,status:e.target.value}):o);render();}catch(err){alert(err.message);load();}});$$('.edit-btn').forEach(b=>b.onclick=()=>openModal(orders.find(o=>o.orderId===b.dataset.order)));}
  function renderReports(){const a=activeOrders(),pending=a.filter(o=>['Novo','Aguardando pagamento'].includes(o.status)),paid=a.filter(o=>PAID.includes(o.status));$('#report-pending-count').textContent=pending.length;$('#report-receivable').textContent=brl(pending.reduce((s,o)=>s+o.total,0));$('#report-received').textContent=brl(paid.reduce((s,o)=>s+o.total,0));$('#report-profit-estimated').textContent=brl(a.reduce((s,o)=>s+o.profit,0));$('#report-profit-obtained').textContent=brl(paid.reduce((s,o)=>s+o.profit,0));$('#report-cost').textContent=brl(a.reduce((s,o)=>s+o.totalCost,0));$('#report-body').innerHTML=a.map(o=>`<tr><td><b>${esc(o.orderId)}</b></td><td>${esc(o.name)}</td><td>${brl(o.subtotal)}</td><td>${brl(o.discount)}</td><td>${brl(o.total)}</td><td>${brl(o.totalCost)}</td><td><b class="profit-value">${brl(o.profit)}</b></td><td>${esc(o.status)}</td></tr>`).join('');}

  function sizeOptions(cat,current='M'){const vals=cat==='Infantil'?['2','4','6','8','10','12','14','16']:['P','M','G','GG','XG','XGG'];return vals.map(v=>`<option ${v===String(current)?'selected':''}>${v}</option>`).join('');}
  function addAdminItem(item={model:'Básico',category:'Masculino',size:'M',quantity:1,childAge:null}){const el=document.createElement('article');el.className='order-item admin-edit-item';el.dataset.id=++editSeq;el.innerHTML=`<div class="order-item-head"><b>Item</b><button type="button" class="remove-item">×</button></div><div class="item-grid"><div class="field"><label>Modelo</label><select class="e-model"><option ${item.model==='Básico'?'selected':''}>Básico</option><option ${item.model==='Premium'?'selected':''}>Premium</option></select></div><div class="field"><label>Categoria</label><select class="e-category"><option ${item.category==='Masculino'?'selected':''}>Masculino</option><option ${item.category==='Feminino'?'selected':''}>Feminino</option><option ${item.category==='Infantil'?'selected':''}>Infantil</option></select></div><div class="field"><label>Tamanho</label><select class="e-size">${sizeOptions(item.category,item.size)}</select></div><div class="field e-age-wrap ${item.category==='Infantil'?'':'hidden'}"><label>Idade</label><input class="e-age" type="number" min="1" max="16" value="${item.childAge||''}"></div><div class="field"><label>Quantidade</label><input class="e-qty" type="number" min="1" value="${Number(item.quantity||1)}"></div></div>`;$('#admin-items').appendChild(el);const cat=el.querySelector('.e-category');cat.onchange=()=>{el.querySelector('.e-age-wrap').classList.toggle('hidden',cat.value!=='Infantil');el.querySelector('.e-size').innerHTML=sizeOptions(cat.value);calcModal();};el.querySelector('.remove-item').onclick=()=>{if($('#admin-items').children.length===1)return alert('O pedido precisa ter pelo menos um item.');el.remove();calcModal();};el.querySelectorAll('select,input').forEach(x=>x.addEventListener('input',calcModal));calcModal();}
  function modalItems(){return $$('#admin-items .admin-edit-item').map(el=>{const model=el.querySelector('.e-model').value,category=el.querySelector('.e-category').value,quantity=Math.max(1,Number(el.querySelector('.e-qty').value||1));return{model,category,size:el.querySelector('.e-size').value,childAge:category==='Infantil'?Number(el.querySelector('.e-age').value||0):null,quantity,unitPrice:PRICES[model],unitCost:COSTS[model],subtotal:PRICES[model]*quantity,costTotal:COSTS[model]*quantity};});}
  function calcModal(){const items=modalItems(),subtotal=items.reduce((s,i)=>s+i.subtotal,0),cost=items.reduce((s,i)=>s+i.costTotal,0),discount=Math.max(0,Number($('#edit-discount').value||0)),total=Math.max(0,subtotal-discount),profit=total-cost;$('#calc-subtotal').textContent=brl(subtotal);$('#calc-cost').textContent=brl(cost);$('#calc-discount').textContent=brl(discount);$('#calc-total').textContent=brl(total);$('#calc-profit').textContent=brl(profit);}
  function openModal(order=null){$('#order-modal').classList.remove('hidden');$('#admin-items').innerHTML='';$('#admin-order-form').reset();if(order){$('#modal-kicker').textContent='Pedido existente';$('#modal-title').textContent=`Editar ${order.orderId}`;$('#edit-order-id').value=order.orderId;$('#edit-name').value=order.name;$('#edit-whatsapp').value=order.whatsapp;$('#edit-city').value=order.city;$('#edit-delivery').value=order.delivery||'A combinar';$('#edit-status').value=order.status||'Novo';$('#edit-notes').value=order.notes||'';$('#edit-discount').value=Number(order.discount||0).toFixed(2);(order.items||[]).forEach(addAdminItem);}else{$('#modal-kicker').textContent='Venda manual';$('#modal-title').textContent='Cadastrar nova venda';$('#edit-order-id').value='';$('#edit-status').value='Pago';$('#edit-discount').value='0';addAdminItem();}calcModal();}
  function closeModal(){$('#order-modal').classList.add('hidden');}
  $('#modal-close').onclick=closeModal;$('#order-modal').addEventListener('click',e=>{if(e.target.id==='order-modal')closeModal();});$('#new-order-btn').onclick=()=>openModal();$('#new-order-btn-2').onclick=()=>openModal();$('#admin-add-item').onclick=()=>addAdminItem();$('#edit-discount').oninput=calcModal;
  $('#admin-order-form').onsubmit=async e=>{e.preventDefault();const existingId=$('#edit-order-id').value,isNew=!existingId,items=modalItems();if(items.some(i=>i.category==='Infantil'&&!i.childAge))return alert('Informe a idade nos itens infantis.');const base=isNew?{orderId:`MM-M${Date.now().toString().slice(-7)}`,createdAt:new Date().toLocaleString('pt-BR'),source:'Manual'}:orders.find(o=>o.orderId===existingId);const order=normalize({...base,name:$('#edit-name').value.trim(),whatsapp:$('#edit-whatsapp').value.trim(),city:$('#edit-city').value.trim(),delivery:$('#edit-delivery').value,status:$('#edit-status').value,notes:$('#edit-notes').value.trim(),payment:'Dinheiro ou PIX',items,discount:Number($('#edit-discount').value||0)});try{await saveOrder(order,isNew);if(isNew)orders.unshift(order);else orders=orders.map(o=>o.orderId===order.orderId?order:o);closeModal();render();}catch(err){alert(err.message);}};
  function exportCsv(){const rows=[['Pedido','Data','Cliente','WhatsApp','Origem','Modelo','Categoria','Tamanho','Quantidade','Preço venda','Custo unitário','Subtotal','Desconto pedido','Total líquido','Custo total','Lucro','Status']];orders.forEach(o=>(o.items||[]).forEach(i=>rows.push([o.orderId,o.createdAt,o.name,o.whatsapp,o.source,i.model,i.category,i.size,i.quantity,i.unitPrice,i.unitCost,i.subtotal,o.discount,o.total,o.totalCost,o.profit,o.status])));const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='relatorio-manto-monumental.csv';a.click();URL.revokeObjectURL(a.href);}
  if(token)showDash();else showLogin();
})();
