-- MANTO MONUMENTAL — BANCO DE DADOS SUPABASE (PRODUÇÃO)
-- Execute todo este arquivo em: Supabase > SQL Editor > New query > Run

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  order_id text not null unique,
  created_at_display text,
  customer_name text not null,
  whatsapp text not null,
  city text not null,
  delivery text default 'A combinar',
  payment text default 'Dinheiro ou PIX',
  neighborhood text,
  address text,
  address_number text,
  complement text,
  notes text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  discount numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  total_cost numeric(10,2) not null default 0,
  profit numeric(10,2) not null default 0,
  status text not null default 'Novo',
  source text not null default 'Site'
);

-- Compatibilidade com instalações anteriores.
alter table public.orders add column if not exists subtotal numeric(10,2) not null default 0;
alter table public.orders add column if not exists discount numeric(10,2) not null default 0;
alter table public.orders add column if not exists total_cost numeric(10,2) not null default 0;
alter table public.orders add column if not exists profit numeric(10,2) not null default 0;
alter table public.orders add column if not exists source text not null default 'Site';

-- O banco recalcula preços/custos/lucro. Isso evita confiar nos totais enviados pelo navegador.
create or replace function public.recalculate_manto_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_items jsonb := '[]'::jsonb;
  item jsonb;
  v_model text;
  v_category text;
  v_size text;
  v_qty integer;
  v_age integer;
  v_price numeric(10,2);
  v_cost numeric(10,2);
  v_subtotal numeric(10,2) := 0;
  v_cost_total numeric(10,2) := 0;
  jwt_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
begin
  if jsonb_typeof(new.items) <> 'array' or jsonb_array_length(new.items) = 0 then
    raise exception 'O pedido precisa conter pelo menos uma camisa.';
  end if;

  for item in select * from jsonb_array_elements(new.items)
  loop
    v_model := case when item->>'model' = 'Premium' then 'Premium' else 'Básico' end;
    v_category := case
      when item->>'category' in ('Masculino','Feminino','Infantil') then item->>'category'
      else 'Masculino'
    end;
    v_size := coalesce(nullif(trim(item->>'size'), ''), 'M');
    v_qty := greatest(1, least(50, coalesce((item->>'quantity')::integer, 1)));
    v_age := case when v_category = 'Infantil' then nullif(item->>'childAge','')::integer else null end;

    if v_model = 'Premium' then
      v_price := 85.00;
      v_cost := 70.00;
    else
      v_price := 65.00;
      v_cost := 55.00;
    end if;

    v_subtotal := v_subtotal + (v_price * v_qty);
    v_cost_total := v_cost_total + (v_cost * v_qty);

    normalized_items := normalized_items || jsonb_build_array(jsonb_build_object(
      'model', v_model,
      'category', v_category,
      'size', v_size,
      'childAge', v_age,
      'quantity', v_qty,
      'unitPrice', v_price,
      'unitCost', v_cost,
      'subtotal', v_price * v_qty,
      'costTotal', v_cost * v_qty
    ));
  end loop;

  new.items := normalized_items;
  new.subtotal := v_subtotal;
  new.total_cost := v_cost_total;

  -- Visitante do site nunca pode definir desconto/status/origem por conta própria.
  if jwt_role = 'anon' then
    new.discount := 0;
    new.status := 'Novo';
    new.source := 'Site';
  else
    new.discount := greatest(0, least(coalesce(new.discount, 0), v_subtotal));
    if new.status not in ('Novo','Aguardando pagamento','Pago','Em produção','Pronto','Entregue','Cancelado') then
      new.status := 'Novo';
    end if;
    if new.source not in ('Site','Manual') then new.source := 'Manual'; end if;
  end if;

  new.total := greatest(0, v_subtotal - new.discount);
  new.profit := new.total - v_cost_total;
  new.payment := 'Dinheiro ou PIX';
  return new;
end;
$$;

drop trigger if exists trg_recalculate_manto_order on public.orders;
create trigger trg_recalculate_manto_order
before insert or update on public.orders
for each row execute function public.recalculate_manto_order();

-- Segurança de produção
-- O público pode SOMENTE inserir novos pedidos.
-- O dashboard só lê/edita pedidos se o usuário autenticado estiver cadastrado em public.manto_admins.

create table if not exists public.manto_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.manto_admins enable row level security;

create or replace function public.is_manto_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.manto_admins a where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_manto_admin() from public;
grant execute on function public.is_manto_admin() to authenticated;

alter table public.orders enable row level security;

-- Menor privilégio possível no Data API.
revoke all on table public.orders from anon, authenticated;
grant insert on table public.orders to anon;
grant select, insert, update on table public.orders to authenticated;

do $$
begin
  if to_regclass('public.orders_id_seq') is not null then
    execute 'grant usage, select on sequence public.orders_id_seq to anon, authenticated';
  end if;
end $$;

drop policy if exists "public can insert orders" on public.orders;
create policy "public can insert orders"
on public.orders for insert
to anon
with check (true);

drop policy if exists "authenticated can read orders" on public.orders;
create policy "authenticated can read orders"
on public.orders for select
to authenticated
using (public.is_manto_admin());

drop policy if exists "authenticated can update orders" on public.orders;
create policy "authenticated can update orders"
on public.orders for update
to authenticated
using (public.is_manto_admin())
with check (public.is_manto_admin());

drop policy if exists "authenticated can insert orders" on public.orders;
create policy "authenticated can insert orders"
on public.orders for insert
to authenticated
with check (public.is_manto_admin());

-- Contador público sem expor nome, WhatsApp ou qualquer dado do cliente.
create or replace function public.public_shirt_count()
returns bigint
language sql
security definer
set search_path = public
as $$
  select coalesce(sum((item->>'quantity')::bigint),0)
  from public.orders o,
       jsonb_array_elements(o.items) item
  where o.status <> 'Cancelado';
$$;

revoke all on function public.public_shirt_count() from public;
grant execute on function public.public_shirt_count() to anon, authenticated;

-- IMPORTANTE: depois de criar seu usuário em Authentication > Users,
-- copie o UUID dele e rode UMA VEZ no SQL Editor:
-- insert into public.manto_admins (user_id) values ('COLE-O-UUID-DO-USUARIO-AQUI');
